@extends('layout.layout')

@section('content')
    <!-- Education Start -->
    <section class="education-section section-content noheadtitle">
        <div class="container">

            <!-- Analysis -->
            <div class="education-content sitecontent-desc">
                <h1>4 Common Active Trading Strategies</h1>
                <h5>1. Day Trading</h5>
                <p>Day trading is perhaps the most well-known active trading style. It's often considered a pseudonym for active trading itself. Day trading, as its name implies, is the method of buying and selling securities within the same day. Positions are closed out within the same day they are taken, and no position is held overnight. Traditionally, day trading is done by professional traders, such as specialists or market makers. However, electronic trading has opened up this practice to novice traders. </p>
                <h5>2. Position Trading</h5>
                <p>Some actually consider position trading to be a buy-and-hold strategy and not active trading. However, position trading, when done by an advanced trader, can be a form of active trading. Position trading uses longer term charts – anywhere from daily to monthly – in combination with other methods to determine the trend of the current market direction. This type of trade may last for several days to several weeks and sometimes longer, depending on the trend.</p>
                <p>Trend traders look for successive higher highs or lower highs to determine the trend of a security. By jumping on and riding the "wave," trend traders aim to benefit from both the up and downside of market movements. Trend traders look to determine the direction of the market, but they do not try to forecast any price levels. Typically, trend traders jump on the trend after it has established itself, and when the trend breaks, they usually exit the position. This means that in periods of high market volatility, trend trading is more difficult and its positions are generally reduced.</p>
                <h5>3. Swing Trading</h5>
                <p>When a trend breaks, swing traders typically get in the game. At the end of a trend, there is usually some price volatility as the new trend tries to establish itself. Swing traders buy or sell as that price volatility sets in. Swing trades are usually held for more than a day but for a shorter time than trend trades. Swing traders often create a set of trading rules based on technical or fundamental analysis.</p>
                <p>These trading rules or algorithms are designed to identify when to buy and sell a security. While a swing-trading algorithm does not have to be exact and predict the peak or valley of a price move, it does need a market that moves in one direction or another. A range-bound or sideways market is a risk for swing traders. </p>
                <h5>4. Scalping</h5>
                <p>Scalping is one of the quickest strategies employed by active traders. It includes exploiting various price gaps caused by bid-ask spreads and order flows. The strategy generally works by making the spread or buying at the bid price and selling at the ask price to receive the difference between the two price points. Scalpers attempt to hold their positions for a short period, thus decreasing the risk associated with the strategy.</p>
                <p>Additionally, a scalper does not try to exploit large moves or move high volumes. Rather, they try to take advantage of small moves that occur frequently and move smaller volumes more often. Since the level of profits per trade is small, scalpers look for more liquid markets to increase the frequency of their trades. And unlike swing traders, scalpers like quiet markets that aren't prone to sudden price movements so they can potentially make the spread repeatedly on the same bid/ask prices. </p>

                <h2>Stop Overthinking & Start Trading</h2>
                <p>Thinking too much. It’s truly a form of mental ‘poison’ that if left unchecked, can consume you and drastically alter your thinking, behavior and even your personality. Needless to say, this negative habit can have disastrous consequences in any area of life: work, personal (relationships), school and especially in trading.</p>
                <p>As with most things, a skilled trader is at his or her best when they are “in the moment” and not thinking too far ahead about all the possible outcomes of a particular trade. Trading is not a game of “chess” like so many people seem to think. It is not going to improve your odds of success by thinking more, researching more or being at your charts more, if it were that easy everyone would be doing it.</p>
                <p>Trading success comes when a person has the proper tools to analyze and make sense of the market as well as the proper mindset that allows them to stay “in the flow” and not think too much or analyze too much.</p>
                <h2>What is “overthinking” in trading and how does it affect your performance?</h2>
                <p>Overthinking can seem like a broad and somewhat obscure topic so it’s important to define what it is so that you know when or if you are doing it so that you can being taking action to stop it.</p>
                <p>We all know that if someone is “overthinking”, they are thinking too much about a topic, to the point where it negatively impacts them. But, the following points outline some specific examples and causes of overthinking in trading. Read along and see if these sound familiar to you:</p>
                <h5>Recency Bias on recent trade outcomes</h5>
                <p>In a recent article I wrote on recency bias in trading, I discussed how traders become overly-influenced by the outcomes of their most recent trades. Essentially, they end up overthinking them and assigning too much weight to those recent trades outcomes.</p>
                <p>For example, if you’re guilty of having recency bias, it means you are thinking and feeling like “this trade” will be a winner “because the last one was” or that “this trade will be a loser because the last one was”. Either way, you’re wrong lol. Your last trade has basically ZERO to do with your next trade. Each trade’s outcome is essentially random from the previous trade(s), so stop thinking about it too much and becoming overly-influenced by the previous trade(s) result. Traders can even start thinking of things like “well since the last 3 trades lost, this one is bound to win” this is another example of recency bias in action. But, this too is wrong and has zero meaning in the real-world. Remember: Your current trade has NOTHING to do with your last trade!</p>
                <h5>General fear of losing money and of being wrong (bruised ego syndrome)</h5>
                <p>Many traders think so much about “losing money” and “being wrong” that they end up not taking perfectly good trades. This problem typically stems from the trader risking too much money or more than they are comfortable with losing on any one trade.</p>
                <p>If you’re going to be a trader, you’re going to be dealing with risk so you have to accept that you can lose and instead of trying to avoid it, just try to manage your losses by managing your risk properly. It comes to down to not risking more per trade than you are comfortable with losing, this is an amount that when you have it at risk you should be able to easily fall asleep at night without worrying about the money or feeling a need to “check the trade real quick”.</p>
                <h5>Not trusting your trading strategy</h5>
                <p>When traders overthink, they often start to doubt their trading strategy and they start thinking likes like “maybe my strategy doesn’t work” or “maybe I should add some trading indicators” etc, this type of self-doubt and overthinking can be very damaging.</p>
                <p>Not trusting your trading strategy is a result of overthinking and not “trusting the process”. Just because you hit a losing trade or even a few in a row, does not mean you should abandon your trading strategy and look for a new one.</p>
                <h5>The “Deer in the headlights” concept: Analysis Paralysis</h5>
                <p>The deer in the headlights “syndrome” is something that happens when traders (once again) overthink about the market and their trades. What happens is that a trader starts to overthink about all the possible scenarios of a trade’s outcome and they end up missing the trade altogether. They end up just staring at the trade take off without them, like a deer caught in the headlights of an oncoming car. You have to be confident and decisive when executing your trades and you can’t allow yourself to get stuck in a cycle of “what ifs” / fear.</p>
                <h5>The Hindsight Trap</h5>
                <p>The hindsight “trap” is something that happens when a trader becomes obsessed with trades after they play out. They torture themselves about missing a trade (deer in headlights) or about exiting a trade too early or a whole host of other things. The bottom-line is that living your trading life in a hindsight “haze” of “what could have been” is detrimental to your long-term trading success. You need to realize that sometimes you’ll miss trades, sometimes you won’t exit a trade exactly when you want to etc. but don’t waste your time thinking about those things too much or you will drive yourself crazy.</p>
                <h5>Trying to “outthink” the market: It’s not a chess game!</h5>
                <p>Many, many traders think they can “outsmart” or “outthink” the market by doing more research or learning the latest new trading system. However, this couldn’t be further from the truth. The market is going to do what it wants, regardless of how much time you spend reading economic reports or studying new trading methods. Unfortunately, trading is not a chess game that you can become better at simply by thinking long enough or hard enough about. Yes, you DO have to do some initial study and get some training to learn an effective trading method like price action analysis, but once you learn a method and you’ve got a weekly and daily trading routine down, any additional time to “researching” “analyzing” or “trying to figure out what will happen next” is futile.</p>
                <h5>Short time-frame charts cause overthinking</h5>
                <p>One sure-fire way to get your brain cells in an overthinking “traffic jam” is to start looking at short time frame charts. The main reason I preach trading the higher timeframe charts is because it simplifies your analysis and smooths out all the noise and random price action on the short time frames. This noise and randomness causes you to overthink and overtrade and generally just sabotages your trading.</p>
                <h5>Checking the news constantly</h5>
                <p>If you’ve been following me for any significant length of time, you know that I generally abhor trading the news because I feel the price action reflects all pertinent variables of a market and also because it causes traders to overthink and over-trade.</p>
                <p>There are thousands of variables that can affect a market at any given moment, so truthfully, to try and analyze or “trade the news” is basically the same thing as trying to “out-think” the market or thinking that if you just “know more” you will “figure out the next move”. All that is true is that the price action is already showing you what the impact of any news on a market, so skip all the news B.S. and just learn to read the footprint of the market; the price action.</p>
                <h2>So, how can you stop overthinking and start trading?</h2>
                <p>So now that you know what overthinking is and how it negatively impacts your trading, here are some simple yet effective solutions on how to overcome this bad habit.</p>
                <h5>Trade What You See, Not What You Think</h5>
                <p>Trade what you’re actually seeing, not just what you think might happen. Traders often think themselves right out of perfectly good trade setups because instead of simply trading what the setup they see in front of them, they start imagining a whole bunch of different scenarios that may or may not happen. You just have to accept that you never know how a trade will play out before it plays out, but when you see a setup that meets your trading strategy criteria, you simply execute the trade and walk away.</p>
                <h5>Ignore the News</h5>
                <p>As mentioned previously, the price action of a market, easily visible on any raw price chart, is the best and most accurate reflection of all the variables affecting a market at any given time. To focus on news or “fundamentals” is simply to distract yourself from the price action and it will set you on a course of overthinking and analyzing. Do yourself a huge favor and stop looking at trading news.</p>
                <h5>Put together a trading plan</h5>
                <p>Perhaps the single most impactful thing you can do to stop overthinking and start trading, is to put together a comprehensive yet concise trading plan. Your trading plan is your “document”, your tangible piece of accountability and guidance. You will learn a lot simply by putting it together and it will become the “glue” that holds your trading together. You should refer back to it every day and read-through it so that you remember what you need to do to not only trade your strategy properly, but to stay on track mentally. Check out my article on how to build a trading plan, for more in-depth trading plan instruction I have a trading plan template in my professional trading course.</p>
                <p>Your trading plan is what will set into motion your trading routine. Routines influences habit and positive habits turn into success.</p>
                <h5>Understand what “gut feel” and trading intuition really is</h5>
                <p>Traders can get easily confused when they hear something like “Don’t think too much, just follow your gut…”So, I want to clarify that statement because gut feel and trading intuition are very important and necessary pieces of the pie.</p>
                <p>The key with gut feel and trading intuition is that it doesn’t come instantly. It’s something that you develop and that will become stronger within you over time and with training and screen time. Essentially, I view it as a “subconscious piece of trading confluence” that adds weight to a trade. It’s your subconscious giving you a ‘green light’ or ‘red light’ to act based on everything you are seeing on the chart and your cumulative trading experience.</p>
                <h5>Practice and implement “set and forget trading”</h5>
                <p>You may not like this, but you need to physically leave your computer sometimes, for longer periods of time than your probably used to. You have to do this so that you don’t overthink and overtrade and get yourself into trouble.</p>
                <p>The hardest part of trading for most people is self-control. One of the most effective and efficient ways to establish self-control in your trading routine is to build-in a section in your trading plan that describes when you will be in front of the charts, for how long and when you will physically leave the charts. You need to remember that you will miss some trades, and that’s OK, the market will be there tomorrow. We are trying to execute a trading edge with discipline, not trade everything that moves.</p>
                <h5>Eliminate fear by controlling what you can and letting go of what you can’t</h5>
                <p>Just like you cannot control another person without their being severe negative consequences in most cases, you absolutely cannot control the market. You can certainly try, but it will result in losing your money and trying to control the market is the best way to describe why most people lose at trading.</p>
                <p>Literally, the ONLY thing you can control in the market is how much you risk per trade, your stop loss placement, your position size, your entry and your exit placement, and that is really about it. You have ZERO control over all the other market players and which way the market will move, Z-E-R-O. Yet, time and time again, traders behave in such a way that shows they are trying to control the market, whether they intend to or not.</p>
                <p>The biggest way to eliminate fear in trading is to control your risk to a dollar amount you are mentally and emotionally OK with potentially losing on any given trade!</p>
                <h5>Stick with your trades</h5>
                <p>This is one is really just about self-discipline. You desperately need to stick with your trades once you enter them. Stop wondering “is there a better trade out there” and then you close out your current trade and enter another one. This is GAMBLING, NOT TRADING!</p>
                <p>Remember, your trading edge (in order to be realized) needs to play out over a series of trades because you never know WHICH particular trade in a series will be a win or a loss; if you do things like close a trade out before it gets a chance to start moving, you are trying to play God of the market and that never works out. Note; there are times when you should close a trade out manually / early, but these are rare and it’s something you shouldn’t do until you’ve had enough experience, training and time.</p>
                <h2>Conclusion</h2>
                <p>To summarize, trading success all comes down to confidence, mental state of mind and trading skill. If you are stuck in a haze of overthinking and overanalyzing the charts, even if you’re a very skilled trader, you’re still not going to do well. The state of your mind and your confidence in your own abilities, as you analyze the charts, are of paramount importance to being able to properly take advantage of your trading edge. Read that last sentence again.</p>
                <p>Tiger Woods, probably the best golfer to have ever played the game of golf, experienced some serious ups and downs in his personal life over the past 10 years. His confidence and mental state of mind went out the window, yet he still possesses the same amazing golfing skill as when he was on top. His career is far from over, but until he finds his right mind and his confidence returns (and hopefully it does for him), he won’t be able to harness his amazing skill and talent to start winning consistently again. This just goes to show that even with amazing skills, if you’re mindset isn’t right, you’re going to fail at whatever it is you’re trying to master (trading, golf, business, school, etc.)</p>
                <p>Trading is so difficult for people because you have to control yourself in the face of constant temptations and constantly changing variables. The tendency and temptation of traders to overthink the entire trading process is immense. This is one reason you need a simplified and structured professional trading education and the guidance to keep you grounded, get you on the right track and help keep you there.</p>
                <h5>How important is psychology in trading?</h5>
                <p>Maintaining the right mindset is one of the most important factors in being a successful trader. Find out how you can improve your trading psychology to minimise the effect of emotions and biases during your time on the markets.</p>
                <p></p>
                <p></p>
                <h5>What is trading psychology?</h5>
                <p>Trading psychology refers to a trader’s mindset during their time on the markets. It can determine the extent to which they succeed in securing a profit or it can provide an explanation as to why a trader incurred heavy losses.</p>
                <p>Innate human characteristics like biases and emotions play a pivotal role in trading psychology. The main focus of learning about trading psychology is to become aware of the various pitfalls which are associated with a negative psychological trait and to develop more positive characteristics. Traders well-versed in trading psychology will generally not act on bias or emotion. They, therefore, stand a better chance of yielding a profit during their time on the markets or, at the very least, of minimising their losses.</p>
                <p>Trading psychology is different for every trader, as it is influenced by each individual’s own emotions and pre-determined biases. Some of the emotions which impact trading are:</p>
                <ul class="ullist ullist-dotted">
                    <li>Happiness</li>
                    <li>Impatience</li>
                    <li>Anger</li>
                    <li>Fear</li>
                    <li>Pride</li>
                </ul>
                <h5>How to improve your trading psychology</h5>
                <p>Improving your trading psychology can most easily be achieved by becoming aware of your own emotions, biases and personality traits. Once you have acknowledged these, you can put a trading plan in place that takes these factors into account with the hope of mitigating any effect that they might have on your decision making.</p>
                <p>As an example, if you are a naturally confident person, you may find that overconfidence and pride hamper your decision-making. For example, you might let losses run in the hope that the market will turnaround, rather than incurring a small loss on your trading account. This could lead to greater losses or the eventual collapse of your trading account.</p>
                <p>To counter this, you might use stops as a way to minimise your losses and to make the decision about when to close a particular trade before you open the position. By doing this, you have become aware of your own biases and emotions as you have made a conscious decision not to act on them but rather, you have taken steps to combat them.</p>
                <h2>How does bias affect trading?</h2>
                <p>Biases affect trading as they are, by definition, a predetermined personal disposition in favour of one thing over another. As a result, they can hinder your decision making during your time on the markets because they might cloud your judgments and lead you to act on gut feeling rather than reasoned fundamental or technical analysis.</p>
                <p>This is because trading bias means that you could be more likely to trade an asset that you have had past success on, or to avoid an asset on which you have incurred a historic loss. It is important that traders are aware of their conscious biases as this can help them overcome them and approach the markets with a more rational and calculated mindset.</p>
                <p>There are five main types of bias:</p>
                <ul class="ullist ullist-dotted">
                    <li><strong>Representative bias</strong> means that you will stick to or be more inclined to replicate previously successful trades. You might do this without carrying out analysis for every trade of this type because in the past, it has paid off for you. However, even if two trades seem similar, it is important to approach every trade on its own merits rather than on historical success</li>
                    <li><strong>Negativity bias</strong> makes you more inclined to only look at the negative side of a trade, rather than acknowledging what went right. This could mean that you scrap an entire strategy when, in fact, you might only have needed to tweak it slightly to turn a profit</li>
                    <li><strong>Status quo bias</strong> means that you will continue to use old strategies or trades rather than exploring new ones – you will stick to the status quo. The danger arises when you fail to assess whether those old methods are still viable in the current market</li>
                    <li><strong>Confirmation bias</strong> is when you seek out, or give greater weight to, news and analysis that confirms your pre-formulated ideas. It may also be that you don’t seek out, or disregard, information which disproves your convictions</li>
                    <li><strong>Gambler’s fallacy</strong> is where you assume that because an asset has been increasing, it will continue to rise. There is no reason to believe that it should, similar to how there is no reason that a coin should land tails side up – rather than heads – after doing so a few times in a row</li>
                </ul>
                <h2>7 tips to avoid emotional trading</h2>
                <ul class="ullist ullist-dotted">
                    <li>Identify your personality traits</li>
                    <li>Develop and follow a trading plan</li>
                    <li>Have patience</li>
                    <li>Be adaptive</li>
                    <li>Take a break after a loss</li>
                    <li>Accept your winnings</li>
                    <li>Keep a trading log</li>
                </ul>
                <h5>Identify your personality traits</h5>
                <p>One of the keys to developing successful trading psychology is identifying your personality traits early on. You will need to be honest with yourself and say if you have impulsive tendencies or if you are prone to acting out of anger or frustration.</p>
                <p>If this is the case, it is important to keep these traits in check while you are actively trading because they can lead you to make rash and ill-advised decisions that have little analytical backing. However, it is also important to play to your personal strengths. For instance, if you are naturally calm and calculated, you can take advantage of these personality traits during your time on the markets.</p>
                <p>Equally as important as identifying and being aware of your personality traits and emotions is recognising your biases, as listed above. Biases are an innate aspect of human nature, but you should be aware of what your individual biases are before opening or closing any trades.</p>
                <h5>Develop and follow a trading plan</h5>
                <p>Having a trading plan is paramount to ensuring that you achieve your goals. A trading plan acts as the blueprint to your trading, and it should highlight your time commitments, your available trading funds, your risk-reward ratio and a trading strategy that you feel comfortable with.</p>
                <p>For instance, a trading plan could say that you were going to commit one hour every morning and evening to trading, and that you will never commit more than 2% of the total value of your portfolio to any one trade. This can help minimise losses and limit the effect of emotions on your trading as the rules for opening or closing a position are already highlighted for you.</p>
                <p>Trading plans should also take into account individual factors that could affect your trading discipline such as your emotions, biases and personality traits. If you make clear what your biases are before you start trading, you might be less inclined to act on them.</p>
                <h5>Have patience</h5>
                <p>Patience is integral to discipline and it is crucial that you have patience with your positions. Acting on emotions like fear can lead you to miss out on a profit by closing a position too early. Trust your analysis and remain patient and disciplined. Equally, when looking to enter a trade, it is important to be patient and wait for the opportune moment rather than just jumping into a trade right then and there.</p>
                <p>For instance, if you were wanting to speculate on some GBP currency pairs like EUR/GBP or GBP/USD, you may want to wait until just before a Bank of England (BoE) announcement as there tends to be increased volatility at this time.</p>
                <h5>Be adaptive</h5>
                <p>While it is important to have a trading plan, remember that no two days on the markets are the same, and winning streaks don’t exist in trading. With this in mind, you should become comfortable in assessing how the markets are different from day to day and adapt accordingly.</p>
                <p>If there is more volatility on one day compared to the day before and the markets are moving particularly unpredictably, you may decide to put your trading activity on hold until you’re sure you understand what is happening. Being adaptive can help to limit your emotions and rule out representative and status quo biases, enabling you to assess each situation on its own merits – ensuring that you are pragmatic during your time on the markets.</p>
                <h5>Take a break after a loss</h5>
                <p>Sometimes after a loss, the best thing you can do is walk away from your trading account for a short while to gather your thoughts and compose yourself – rather than rushing into another trade in an attempt to regain some of your losses.</p>
                <p>The best traders are those that take their losses and use them as learning opportunities. They will typically take a few minutes to themselves before going back to their platform, using this time to assess what went wrong for that particular trade in the hope that they might avoid making the same mistake in the future.</p>
                <p>In doing so, they keep emotions like pride or fear in check by letting themselves cool off before approaching the next trade with a clear head and sound judgment.</p>
                <h5>Accept your winnings</h5>
                <p>Just as important as taking a break after a loss is to quit while you are ahead and take your winnings. A succession of wins or one particularly big win can make you feel invincible and you could subsequently rush into another position to try and do it all over again.</p>
                <p>You might even open a succession of new positions in the belief that none of them will fail because today is ‘your day’ on the markets. This could cause you to take unnecessary risks or diversify your portfolio too quickly without doing analysis into each of the respective markets.</p>
                <p>Happiness can be just as dangerous as anger during your time on the markets and, as such, it is important to recognise when it might be impairing your decision making or could be having a negative impact on your trading psychology.</p>
                <h5>Keep a trading log</h5>
                <p>A trading log will enable you to record all of your losses and wins, as well as the emotions that you were experiencing during that particular trade. As a result, it is the culmination of all the previous points in this article, and can be used to assess whether what you did at any one point in time was a good decision or not.</p>
                <p>For instance, a trading log can be used to record a time when you chose to cut your losses and the eventual price that the asset hit. By doing this, you can see if you made the right decision or not. Equally, it can be used to record when you accepted your winnings and if your emotions played a role in whether you chose to close that position too early or a little late.</p>
                <h2>Trading psychology summed up</h2>
                <p>Trading psychology is all about your mindset during your time on the markets and it can inform an explanation of your profits or losses</p>
                <p>It is important for you to be aware of your own weaknesses and biases before entering a position but, equally, it is important that you understand your own strengths</p>
                <p>Learn from your wins as much as your losses, but remember that winning streaks don’t exist in trading and that each position should be assessed on its own merits</p>
                <p>Knowing when to take a profit or cut a loss can be the difference between a good day and a bad day on the markets</p>
                <p>Keep a trading log as a record for you to see what worked, what didn’t work, and whether your decision at the time was correct in hindsight.</p>
            </div>
            <!-- Analysis -->

        </div>
    </section>
    <!-- Education End -->


    <x-common-about-us/>
@endsection
